SET TimeZone = 'UTC';

CREATE SCHEMA IF NOT EXISTS mart_;

CREATE TABLE IF NOT EXISTS mart_.genre_weekly (
    week_start DATE NOT NULL,
    iso_year INTEGER NOT NULL,
    iso_week INTEGER NOT NULL,
    canonical_genre VARCHAR NOT NULL,

    conversation_mentions BIGINT NOT NULL,
    conversation_likes BIGINT NOT NULL,
    conversation_reposts BIGINT NOT NULL,
    conversation_replies BIGINT NOT NULL,
    conversation_score_raw DOUBLE NOT NULL,
    conversation_score_shrunk DOUBLE NOT NULL,
    conversation_share_raw DOUBLE NOT NULL,
    conversation_share_shrunk DOUBLE NOT NULL,
    conversation_prior_share DOUBLE NOT NULL,
    conversation_effective_n DOUBLE NOT NULL,
    conversation_shrinkage_weight DOUBLE NOT NULL,

    listening_playcount_delta BIGINT,
    listening_listeners_delta BIGINT,
    listening_score_raw DOUBLE,

    supply_release_groups BIGINT NOT NULL,
    supply_rate_shrunk DOUBLE NOT NULL,
    supply_prior_mean DOUBLE NOT NULL,
    supply_effective_n DOUBLE NOT NULL,
    supply_shrinkage_weight DOUBLE NOT NULL,

    conversation_index DOUBLE NOT NULL,
    conversation_index_ci_low DOUBLE NOT NULL,
    conversation_index_ci_high DOUBLE NOT NULL,
    listening_index DOUBLE,
    listening_index_ci_low DOUBLE,
    listening_index_ci_high DOUBLE,
    supply_index DOUBLE NOT NULL,
    supply_index_ci_low DOUBLE NOT NULL,
    supply_index_ci_high DOUBLE NOT NULL,
    opportunity DOUBLE,
    opportunity_ci_low DOUBLE,
    opportunity_ci_high DOUBLE,
    discovery_gap DOUBLE,
    discovery_gap_ci_low DOUBLE,
    discovery_gap_ci_high DOUBLE,

    conversation_ewma DOUBLE NOT NULL,
    conversation_ewma_ci_low DOUBLE NOT NULL,
    conversation_ewma_ci_high DOUBLE NOT NULL,
    listening_ewma DOUBLE,
    listening_ewma_ci_low DOUBLE,
    listening_ewma_ci_high DOUBLE,
    supply_ewma DOUBLE NOT NULL,
    supply_ewma_ci_low DOUBLE NOT NULL,
    supply_ewma_ci_high DOUBLE NOT NULL,
    conversation_spike BOOLEAN NOT NULL,
    listening_spike BOOLEAN NOT NULL,
    supply_spike BOOLEAN NOT NULL,
    breakout_precursor BOOLEAN NOT NULL,

    conversation_post_uris VARCHAR[] NOT NULL,
    listening_artist_keys VARCHAR[] NOT NULL,
    supply_release_group_mbids VARCHAR[] NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (week_start, canonical_genre)
);

CREATE TABLE IF NOT EXISTS mart_.ecosystem_weekly (
    week_start DATE PRIMARY KEY,
    iso_year INTEGER NOT NULL,
    iso_week INTEGER NOT NULL,
    shannon_listening_entropy DOUBLE,
    shannon_listening_entropy_ci_low DOUBLE,
    shannon_listening_entropy_ci_high DOUBLE,
    effective_genres DOUBLE,
    effective_genres_ci_low DOUBLE,
    effective_genres_ci_high DOUBLE,
    conversation_hhi DOUBLE,
    conversation_hhi_ci_low DOUBLE,
    conversation_hhi_ci_high DOUBLE,
    listening_top10_share DOUBLE,
    listening_top10_share_ci_low DOUBLE,
    listening_top10_share_ci_high DOUBLE,
    scene_churn_jaccard_4w DOUBLE,
    scene_churn_jaccard_4w_ci_low DOUBLE,
    scene_churn_jaccard_4w_ci_high DOUBLE,
    breakout_genres VARCHAR[] NOT NULL,
    canonical_genre_count INTEGER NOT NULL,
    listening_observed_genres INTEGER NOT NULL,
    opportunity_observed_genres INTEGER NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL
);
