SET TimeZone = 'UTC';

CREATE SCHEMA IF NOT EXISTS mart_;

CREATE TABLE IF NOT EXISTS mart_.genre_weekly_v2 (
    taxonomy_version VARCHAR NOT NULL,
    week_start DATE NOT NULL,
    iso_year INTEGER NOT NULL,
    iso_week INTEGER NOT NULL,
    genre_id VARCHAR NOT NULL,
    display_name VARCHAR NOT NULL,
    macro_family_id VARCHAR NOT NULL,
    parent_genre_id VARCHAR,
    coverage_state VARCHAR NOT NULL,
    estimate_status VARCHAR NOT NULL,
    estimate_eligible BOOLEAN NOT NULL,
    conversation_score_raw DOUBLE,
    listening_playcount_delta DOUBLE,
    listening_listeners_delta DOUBLE,
    listening_score_raw DOUBLE,
    supply_release_groups_raw DOUBLE,
    conversation_score_shrunk DOUBLE,
    conversation_effective_n DOUBLE,
    conversation_subgenre_shrinkage_weight DOUBLE,
    conversation_family_shrinkage_weight DOUBLE,
    conversation_combined_shrinkage_weight DOUBLE,
    listening_effective_n DOUBLE,
    listening_shrinkage_weight DOUBLE,
    supply_rate_shrunk DOUBLE,
    supply_family_prior_mean DOUBLE,
    supply_global_prior_mean DOUBLE,
    supply_effective_n DOUBLE,
    supply_subgenre_shrinkage_weight DOUBLE,
    supply_family_shrinkage_weight DOUBLE,
    supply_combined_shrinkage_weight DOUBLE,
    breakout_global BOOLEAN,
    breakout_peer_family BOOLEAN,
    conversation_post_uris VARCHAR[] NOT NULL,
    listening_artist_keys VARCHAR[] NOT NULL,
    supply_release_group_mbids VARCHAR[] NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (taxonomy_version, week_start, genre_id)
);

CREATE TABLE IF NOT EXISTS mart_.metric_estimates_v2 (
    taxonomy_version VARCHAR NOT NULL,
    week_start DATE NOT NULL,
    scope_type VARCHAR NOT NULL,
    scope_id VARCHAR NOT NULL,
    macro_family_id VARCHAR NOT NULL,
    context VARCHAR NOT NULL,
    metric_name VARCHAR NOT NULL,
    estimate_status VARCHAR NOT NULL,
    estimate DOUBLE,
    ci_low DOUBLE,
    ci_high DOUBLE,
    ewma DOUBLE,
    ewma_ci_low DOUBLE,
    ewma_ci_high DOUBLE,
    spike BOOLEAN,
    computed_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (
        taxonomy_version,
        week_start,
        scope_type,
        scope_id,
        context,
        metric_name
    ),
    CHECK (scope_type IN ('genre', 'macro_family')),
    CHECK (context IN ('global', 'peer_family')),
    CHECK (
        metric_name IN (
            'conversation',
            'listening',
            'supply',
            'opportunity',
            'discovery_gap'
        )
    )
);

CREATE TABLE IF NOT EXISTS mart_.macro_family_weekly_v2 (
    taxonomy_version VARCHAR NOT NULL,
    week_start DATE NOT NULL,
    iso_year INTEGER NOT NULL,
    iso_week INTEGER NOT NULL,
    macro_family_id VARCHAR NOT NULL,
    display_name VARCHAR NOT NULL,
    total_genres INTEGER NOT NULL,
    eligible_genres INTEGER NOT NULL,
    estimate_status VARCHAR NOT NULL,
    coverage_state_counts_json VARCHAR NOT NULL,
    conversation_score_raw DOUBLE,
    listening_score_raw DOUBLE,
    supply_release_groups_raw DOUBLE,
    conversation_effective_n DOUBLE,
    listening_effective_n DOUBLE,
    supply_effective_n DOUBLE,
    breakout_genres_global VARCHAR[] NOT NULL,
    breakout_genres_peer VARCHAR[] NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (taxonomy_version, week_start, macro_family_id)
);

CREATE TABLE IF NOT EXISTS mart_.ecosystem_weekly_v2 (
    taxonomy_version VARCHAR NOT NULL,
    week_start DATE NOT NULL,
    iso_year INTEGER NOT NULL,
    iso_week INTEGER NOT NULL,
    scope_type VARCHAR NOT NULL,
    scope_id VARCHAR NOT NULL,
    estimate_status VARCHAR NOT NULL,
    listening_entropy DOUBLE,
    listening_entropy_ci_low DOUBLE,
    listening_entropy_ci_high DOUBLE,
    effective_genres DOUBLE,
    effective_genres_ci_low DOUBLE,
    effective_genres_ci_high DOUBLE,
    conversation_hhi DOUBLE,
    conversation_hhi_ci_low DOUBLE,
    conversation_hhi_ci_high DOUBLE,
    listening_top_share DOUBLE,
    listening_top_share_ci_low DOUBLE,
    listening_top_share_ci_high DOUBLE,
    listening_top_share_k INTEGER NOT NULL,
    churn_jaccard_4w DOUBLE,
    churn_jaccard_4w_ci_low DOUBLE,
    churn_jaccard_4w_ci_high DOUBLE,
    breakout_genres VARCHAR[] NOT NULL,
    eligible_genres INTEGER NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (taxonomy_version, week_start, scope_type, scope_id),
    CHECK (scope_type IN ('global', 'macro_family'))
);
