INSERT INTO mart_.genre_weekly_v2 (
    taxonomy_version,
    week_start,
    iso_year,
    iso_week,
    genre_id,
    display_name,
    macro_family_id,
    parent_genre_id,
    coverage_state,
    estimate_status,
    estimate_eligible,
    conversation_score_raw,
    listening_playcount_delta,
    listening_listeners_delta,
    listening_score_raw,
    supply_release_groups_raw,
    conversation_score_shrunk,
    conversation_effective_n,
    conversation_subgenre_shrinkage_weight,
    conversation_family_shrinkage_weight,
    conversation_combined_shrinkage_weight,
    listening_effective_n,
    listening_shrinkage_weight,
    supply_rate_shrunk,
    supply_family_prior_mean,
    supply_global_prior_mean,
    supply_effective_n,
    supply_subgenre_shrinkage_weight,
    supply_family_shrinkage_weight,
    supply_combined_shrinkage_weight,
    breakout_global,
    breakout_peer_family,
    conversation_post_uris,
    listening_artist_keys,
    supply_release_group_mbids,
    computed_at
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
);
