INSERT INTO mart_.genre_weekly (
    week_start,
    iso_year,
    iso_week,
    canonical_genre,
    conversation_mentions,
    conversation_likes,
    conversation_reposts,
    conversation_replies,
    conversation_score_raw,
    conversation_score_shrunk,
    conversation_share_raw,
    conversation_share_shrunk,
    conversation_prior_share,
    conversation_effective_n,
    conversation_shrinkage_weight,
    listening_playcount_delta,
    listening_listeners_delta,
    listening_score_raw,
    supply_release_groups,
    supply_rate_shrunk,
    supply_prior_mean,
    supply_effective_n,
    supply_shrinkage_weight,
    conversation_index,
    conversation_index_ci_low,
    conversation_index_ci_high,
    listening_index,
    listening_index_ci_low,
    listening_index_ci_high,
    supply_index,
    supply_index_ci_low,
    supply_index_ci_high,
    opportunity,
    opportunity_ci_low,
    opportunity_ci_high,
    discovery_gap,
    discovery_gap_ci_low,
    discovery_gap_ci_high,
    conversation_ewma,
    conversation_ewma_ci_low,
    conversation_ewma_ci_high,
    listening_ewma,
    listening_ewma_ci_low,
    listening_ewma_ci_high,
    supply_ewma,
    supply_ewma_ci_low,
    supply_ewma_ci_high,
    conversation_spike,
    listening_spike,
    supply_spike,
    breakout_precursor,
    conversation_post_uris,
    listening_artist_keys,
    supply_release_group_mbids,
    computed_at
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
);
